version: '3.8'
services:
  db:
    image: postgres:14.4-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - '5433:5432'
    volumes:
      - db:/var/lib/postgres/data
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
volumes:
  db:
    driver: local